# node-webapp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-webapp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-webapp-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-webapp-app
    spec:
      containers:
        - image: mentoracr.azurecr.io/node-webapp:latest
          name: node-webapp
          ports:
            - containerPort: 8080
              name: node-webapp
          resources:
            requests:
              cpu: "0.3"
              memory: "64Mi"
            limits:
              cpu: "0.5"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: node-webapp-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
  selector:
    app: node-webapp-app